version: '3'

services:
  api_bazar:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://api_bazar_sql:5432/api_bazar
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      api_bazar_sql:
        condition: service_healthy
        
  api_bazar_sql:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: api_bazar
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 5s
      retries: 10
